### ISSUE TITLE
Player revive error spam

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#199]
Player revive spams you with errors whenever you die.

**Comment by tyon2006** [comment]
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field com.creativemd.creativecore.common.gui.controls.gui.GuiLabel.caption from class com.creativemd.playerrevive.gui.SubGuiRevive
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field com.creativemd.creativecore.common.gui.controls.gui.GuiLabel.caption from class com.creativemd.playerrevive.gui.SubGuiRevive
    at com.creativemd.playerrevive.gui.SubGuiRevive.receiveContainerPacket(SubGuiRevive.java:175)
    at com.creativemd.creativecore.common.packet.gui.GuiNBTPacket.executeClient(GuiNBTPacket.java:35)
    at com.creativemd.creativecore.common.packet.PacketReciever$1.run(PacketReciever.java:86)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

**Comment by tyon2006** [comment]
Looks like we need to remove PlayerRevive or attempt an update and see if mystical lib stop vomiting with sponge installed.
